# Frontend's Dockerfile

# Use the official Node.js image as a base

# syntax=docker/dockerfile:1
# Build stage
FROM node:18-alpine AS build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps 

# Copy the rest of the application code
COPY . .

# Build the app
# For production environment
ENV NODE_ENV=production  
RUN npm run build

# Serve the app using a lightweight server
FROM nginx:alpine

# Copy the nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy the build output to Nginx's html directory
COPY --from=build /app/dist /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
